spring.application.name=SchoolManagementSystem

spring.datasource.url=${MYSQL_URL:jdbc:mysql://mysql.railway.internal:3306/railway}
spring.datasource.username=root
spring.datasource.password=${MYSQL_ROOT_PASSWORD:bikNaMeJZehevqwhYoIkllXrTjgwMGOS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

subscription.code = ${SUBSCRIPTION_CODE}
jwt.secret = ${JWT_SECRET}
jwt.expiration = 86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080